/* NO EXPROPIACION DE RECURSOS. Una vez adquirido un recurso, 
no se le puede arrebatar por otro proceso.
*
*
*EXPULSIÓN DE RECURSOS
*
*Si un pintor ya tiene cogido su primer color (y ya ha 
pintado con él), pero cuando va a coger el segundo color 
se encuentra con que está ocupado, entonces deja el primer 
color y empieza otra vez el ciclo.
*
*Para ello necesitaremos dos métodos tomaColor(i) que 
distingan si es el primer color o es el segundo. 
El método tomaColor1(i) es el mismo que el tomaColor(i) 
original, pero tomaColor2(i) se ha modificado de la 
siguiente forma: si el color está libre lo coge, pero si 
está ocupado, devuelve negro (Color.black) y no se queda 
esperando.
*
*Ahora los pintores, si al intentar tomar el segundo color, 
reciben negro, dejan el primer color que ya habían cogido y 
empiezan de nuevo el ciclo.
*
*De esta forma, el sistema es menos eficiente, pero no puede
bloquearse.
*/


package colores.noExpropiacionRecursos;

import colores.*;

public class Colores_NER extends javax.swing.JFrame
{
    /** Creates new form Coloress */
    public Colores_NER()
    {
        initComponents();
        Paleta_NER mezclas = new Paleta_NER();
        Pintor_NER p1 = new Pintor_NER(jButton1,mezclas,0);
        Pintor_NER p2 = new Pintor_NER(jButton2,mezclas,1);
        Pintor_NER p3 = new Pintor_NER(jButton3,mezclas,2);
        Pintor_NER p4 = new Pintor_NER(jButton4,mezclas,3);
        p1.start();
        p2.start();
        p3.start();
        p4.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colores_NER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration                   
}
