/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Metodos;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author laura y victor
 */
public class moduloControl extends javax.swing.JFrame {

    /**
     * Creates new form moduloControl
     */
    
    Metodos acceso;
    
    public moduloControl() throws NotBoundException, MalformedURLException, RemoteException {
        initComponents();
        this.setLocationRelativeTo(null);  //ajustarlo en el medio de la pantalla
        acceso = (Metodos) Naming.lookup("//127.0.0.1/Metodos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDetener = new javax.swing.JButton();
        botonReanudar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonDetener.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonDetener.setForeground(new java.awt.Color(0, 0, 0));
        botonDetener.setText("DETENER");
        botonDetener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDetenerMouseClicked(evt);
            }
        });
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        getContentPane().add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 60));

        botonReanudar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonReanudar.setForeground(new java.awt.Color(0, 0, 0));
        botonReanudar.setText("REANUDAR");
        botonReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReanudarActionPerformed(evt);
            }
        });
        getContentPane().add(botonReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 150, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Módulo de Control");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        try {
            // TODO add your handling code here:
            acceso.cerrar();
        } catch (RemoteException ex) {
            Logger.getLogger(moduloControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonDetenerActionPerformed

   
    private void botonDetenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDetenerMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonDetenerMouseClicked

    
    private void botonReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReanudarActionPerformed
        try {
            // TODO add your handling code here:
            acceso.abrir();
        } catch (RemoteException ex) {
            Logger.getLogger(moduloControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonReanudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moduloControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moduloControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moduloControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moduloControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new moduloControl().setVisible(true);
                } catch (NotBoundException ex) {
                    Logger.getLogger(moduloControl.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(moduloControl.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(moduloControl.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonReanudar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
